# Detekt Configuration for Smart Daily Expense Tracker
# Kotlin static analysis tool configuration

build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

processors:
  active: true

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FileBasedFindingsReport'

output-reports:
  active: true
  exclude:
    - 'HtmlOutputReport'
    - 'XmlOutputReport'
    - 'TxtOutputReport'
    - 'SarifOutputReport'

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
  NewLineAtEndOfFile:
    active: true
  TrailingWhitespace:
    active: true

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LargeClass:
    active: true
    threshold: 150
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7

naming:
  active: true

potential-bugs:
  active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true

performance:
  active: true
  SpreadOperator:
    active: true
  ArrayPrimitive:
    active: true

# Formatting rules are handled by ktlint or other formatting tools
