package com.avi.smartdailyexpensetracker.data.service

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import java.io.File

class FileSharingService(private val context: Context) {
    
    companion object {
        private const val AUTHORITY = "com.avi.smartdailyexpensetracker.fileprovider"
    }
    
    fun shareFile(
        file: File,
        mimeType: String,
        title: String = "Share Expense Report"
    ): Intent {
        val uri = FileProvider.getUriForFile(context, AUTHORITY, file)
        
        return Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, title)
            putExtra(Intent.EXTRA_TEXT, "Expense report generated by Smart Daily Expense Tracker")
            
            // Grant temporary permissions
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
    }
    
    fun sharePdfReport(file: File): Intent {
        return shareFile(file, "application/pdf", "Share PDF Report")
    }
    
    fun shareCsvReport(file: File): Intent {
        return shareFile(file, "text/csv", "Share CSV Report")
    }
    
    fun shareViaEmail(
        file: File,
        mimeType: String,
        subject: String = "Expense Report",
        body: String = "Please find attached the expense report."
    ): Intent {
        val uri = FileProvider.getUriForFile(context, AUTHORITY, file)
        
        return Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, subject)
            putExtra(Intent.EXTRA_TEXT, body)
            putExtra(Intent.EXTRA_EMAIL, arrayOf("")) // Empty array for user to fill
            
            // Grant temporary permissions
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
    }
    
    fun shareViaWhatsApp(file: File, mimeType: String): Intent {
        val uri = FileProvider.getUriForFile(context, AUTHORITY, file)
        
        return Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_TEXT, "Expense report from Smart Daily Expense Tracker")
            
            // Set WhatsApp package
            setPackage("com.whatsapp")
            
            // Grant temporary permissions
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
    }
    
    fun shareViaTelegram(file: File, mimeType: String): Intent {
        val uri = FileProvider.getUriForFile(context, AUTHORITY, file)
        
        return Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_TEXT, "Expense report from Smart Daily Expense Tracker")
            
            // Set Telegram package
            setPackage("org.telegram.messenger")
            
            // Grant temporary permissions
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
    }
    
    fun getShareChooserIntent(
        file: File,
        mimeType: String,
        title: String = "Share Expense Report"
    ): Intent {
        val shareIntent = shareFile(file, mimeType, title)
        return Intent.createChooser(shareIntent, title)
    }
    
    fun canShareViaWhatsApp(): Boolean {
        return try {
            context.packageManager.getPackageInfo("com.whatsapp", 0)
            true
        } catch (e: Exception) {
            false
        }
    }
    
    fun canShareViaTelegram(): Boolean {
        return try {
            context.packageManager.getPackageInfo("org.telegram.messenger", 0)
            true
        } catch (e: Exception) {
            false
        }
    }
}
