package com.avi.smartdailyexpensetracker.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF1976D2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBDEFB)
val md_theme_light_onPrimaryContainer = Color(0xFF0D47A1)
val md_theme_light_secondary = Color(0xFF388E3C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC8E6C9)
val md_theme_light_onSecondaryContainer = Color(0xFF1B5E20)
val md_theme_light_tertiary = Color(0xFFFF9800)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE0B2)
val md_theme_light_onTertiaryContainer = Color(0xFFE65100)
val md_theme_light_error = Color(0xFFD32F2F)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFCDD2)
val md_theme_light_onErrorContainer = Color(0xFFB71C1C)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF212121)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF212121)
val md_theme_light_surfaceVariant = Color(0xFFF5F5F5)
val md_theme_light_onSurfaceVariant = Color(0xFF424242)
val md_theme_light_outline = Color(0xFFBDBDBD)
val md_theme_light_outlineVariant = Color(0xFFE0E0E0)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF90CAF9)
val md_theme_dark_onPrimary = Color(0xFF0D47A1)
val md_theme_dark_primaryContainer = Color(0xFF1565C0)
val md_theme_dark_onPrimaryContainer = Color(0xFFE3F2FD)
val md_theme_dark_secondary = Color(0xFF81C784)
val md_theme_dark_onSecondary = Color(0xFF1B5E20)
val md_theme_dark_secondaryContainer = Color(0xFF2E7D32)
val md_theme_dark_onSecondaryContainer = Color(0xFFC8E6C9)
val md_theme_dark_tertiary = Color(0xFFFFB74D)
val md_theme_dark_onTertiary = Color(0xFFE65100)
val md_theme_dark_tertiaryContainer = Color(0xFFF57C00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE0B2)
val md_theme_dark_error = Color(0xFFEF5350)
val md_theme_dark_onError = Color(0xFFB71C1C)
val md_theme_dark_errorContainer = Color(0xFFC62828)
val md_theme_dark_onErrorContainer = Color(0xFFFFCDD2)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE0E0E0)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFE0E0E0)
val md_theme_dark_surfaceVariant = Color(0xFF2D2D2D)
val md_theme_dark_onSurfaceVariant = Color(0xFFBDBDBD)
val md_theme_dark_outline = Color(0xFF424242)
val md_theme_dark_outlineVariant = Color(0xFF616161)

// Category Colors (consistent across themes)
val categoryStaff = Color(0xFF1976D2)
val categoryTravel = Color(0xFF388E3C)
val categoryFood = Color(0xFFFF9800)
val categoryUtility = Color(0xFF9C27B0)

// Status Colors
val successColor = Color(0xFF4CAF50)
val warningColor = Color(0xFFFF9800)
val errorColor = Color(0xFFF44336)
val infoColor = Color(0xFF2196F3)
