name: Quick CI

on:
  push:
    branches: [ feature/*, bugfix/*, hotfix/* ]
  pull_request:
    branches: [ main, develop ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest --console=plain
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --console=plain
      
    - name: Run Lint
      run: ./gradlew lintDebug --console=plain
